name: Add GitHub Label to IRM Incident

on:
  issues:
    types: [labeled]

jobs:
  add-ghlabel:
    runs-on: ubuntu-latest

    steps:
      - name: Extract issue details
        id: extract
        run: |
          echo "📋 Extracting issue info..."
          echo "ISSUE_BODY<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.issue.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
          echo "LABEL_NAME=${{ github.event.label.name }}" >> $GITHUB_ENV

      - name: Parse incident ID from issue body
        id: parse_incident
        run: |
          echo "🔍 Searching for incident ID..."
          INCIDENT_ID=$(echo "$ISSUE_BODY" | grep -Eo '([Ii]ncident[ _-]?[Ii][dD])[: ]*\**[[:space:]]*([0-9]+)' | grep -Eo '[0-9]+' | head -1)
          
          if [ -z "$INCIDENT_ID" ]; then
            echo "❌ Could not find incidentID in issue body"
            echo "Issue body was:"
            echo "$ISSUE_BODY"
            exit 1
          fi

          echo "✅ Found incidentID: $INCIDENT_ID"
          echo "INCIDENT_ID=$INCIDENT_ID" >> $GITHUB_ENV

      - name: Add GitHub Label to IRM Incident
        env:
          STACK_URL: https://ep.amer.cloud.demokit.grafana.com
          IRM_API_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY_INCIDENT }}
        run: |
          echo "🚀 Adding label to IRM incident"

          key="ghLabel"
          value="$LABEL_NAME"

          echo "Using key=$key, value=$value"
          echo "Target incident: $INCIDENT_ID"

          # 1️⃣ Add label value to IRM
          payload_value=$(jq -n --arg key "$key" --arg value "$value" \
            '{key: $key, value: $value}')

          curl -s -X POST "$STACK_URL/api/plugins/grafana-irm-app/resources/api/FieldsService.AddLabelValue" \
            -H "Authorization: Bearer $IRM_API_KEY" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -H "x-grafana-org-id: 1" \
            -d "$payload_value" \
            -o /dev/null

          # 2️⃣ Add label to incident
          payload_label=$(jq -n --arg incidentID "$INCIDENT_ID" --arg key "$key" --arg label "$value" \
            '{incidentID: $incidentID, label: { key: $key, label: $label }}')

          curl -s -X POST "$STACK_URL/api/plugins/grafana-irm-app/resources/api/IncidentsService.AddLabel" \
            -H "Authorization: Bearer $IRM_API_KEY" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -H "x-grafana-org-id: 1" \
            -d "$payload_label" \
            -o /dev/null

          echo "✅ Successfully added ghLabel:'$value' to IRM incident $INCIDENT_ID"
